remote_theme: pages-themes/cayman@v0.2.0
plugins:
- jekyll-remote-theme # add this line to the plugins list if you already have one

title: [Portfolio]
description: [This website will eventually be my comprehensive portfolio.]

baseurl: "jyankura-protfolio"
url: "https://jyankura-github.github.io/"